# Local inventory default version overrides to pass configuration checks
cas_version: "6.6.6"
userdetails_version: "3.2.0"
user_details_version: "3.2.0"
cas_management_version: "6.6.6"
apikey_version: "1.7.0"
collectory_version: "3.2.0"
ala_namematching_service_version: "1.0.0"
userdetails_host_name: "auth.ala.org.au"
apikey_host_name: "auth.ala.org.au"
cas_management_host_name: "auth.ala.org.au"
cas_server_name: "https://auth.ala.org.au"
cas_host_name: "auth.ala.org.au"
org_short_name: "TEST"
org_name_long: "Test Organization"
cas_context_path: "cas"
userdetails_context_path: "userdetails"
apikey_context_path: "apikey"
pac4j_cookie_encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
pac4j_cookie_signing_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_tgc_crypto_signingKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_tgc_crypto_encryptionKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_webflow_crypto_signingKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_webflow_crypto_encryptionKey: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_webflow_signing_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_webflow_encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_oauth_encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_oauth_signing_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_oauth_access_token_encryption_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_oauth_access_token_signing_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
cas_mail_server: "mailhog"
cas_mail_port: "1025"
userdetails_base_url: "https://auth.ala.org.au"
user_create_password: "password"
endpoints_enabled: true
userdetails_server_name: "https://auth.ala.org.au"
apikey_server_name: "https://auth.ala.org.au"
cas_management_server_name: "https://auth.ala.org.au"
apikey_db_username: "apikey"
apikey_db_password: "password"
api_key: "TEST-KEY"
sightings_base_url: "https://sightings.ala.org.au"
spatial_base_url: "https://spatial.ala.org.au"
volunteer_base_url: "https://volunteer.ala.org.au"
lists_base_url: "https://lists.ala.org.au"
biocache_base_url: "https://biocache.ala.org.au"
sandbox_base_url: "https://sandbox.ala.org.au"
alerts_base_url: "https://alerts.ala.org.au"
oauth_providers_flickr_key: "flickr"
oauth_providers_flickr_secret: "flickr"
ala_base_url: "https://www.ala.org.au"
bootadmin_enabled: false
spring_session_enabled: false
spring_session_store_type: "none"
user_store_db_encoding_salt: "salt"
user_store_db_encoding_algorithm: "bcrypt"
user_store_db_bcrypt_strength: 10
use_openjdk17: false
use_openjdk11: false
use_openjdk8: true
use_la_site_certs: false
ssl_certificate_server_dir: "/etc/letsencrypt/live"
ssl_cert_file: "fullchain.pem"
ssl_key_file: "privkey.pem"
collectory_db_user: "collectory"
collectory_db_name: "collectory"
mysql_root_password: "password"
collectory_db_host_address: "mysql"
