// Living Atlas deployment smoke/e2e suite.
// Inspired by & adapted from inbo/vlaams-biodiversiteitsportaal (MPL-2.0):
//   https://github.com/inbo/vlaams-biodiversiteitsportaal
import { defineConfig } from "cypress";
import * as fs from "fs";

// Targets are INVENTORY-DRIVEN: the deployment's config-gen emits e2e-targets.json with
// fully-resolved per-service URLs (subdomain or path, whatever the inventory dictates).
// We only choose WHICH manifest to load here — there is no hardcoded service table.
const targetEnv = process.env.CYPRESS_TARGET_ENV || "lademo";
const targetsFile =
  process.env.CYPRESS_TARGETS_FILE || "/data/docker-compose/e2e-targets.json";

if (!fs.existsSync(targetsFile)) {
  throw new Error(
    `e2e-targets manifest not found at '${targetsFile}'.\n` +
      `It is generated by the deployment (config-gen writes it to ` +
      `{{ docker_compose_data_dir }}/e2e-targets.json). ` +
      `Set CYPRESS_TARGETS_FILE to point at a generated manifest.`,
  );
}
const targets = JSON.parse(fs.readFileSync(targetsFile, "utf8"));

module.exports = defineConfig({
  viewportWidth: 1280,
  viewportHeight: 720,
  retries: { runMode: 2, openMode: 0 },
  e2e: {
    baseUrl: targets.root,
    env: {
      TARGET_ENV: targetEnv,
      TARGETS: targets,
      LADEMO_USERNAME: process.env.CYPRESS_LADEMO_USERNAME,
      LADEMO_PASSWORD: process.env.CYPRESS_LADEMO_PASSWORD,
      ENABLE_AUTH_TESTS: process.env.CYPRESS_ENABLE_AUTH_TESTS,
    },
    setupNodeEvents(on) {
      // Delete videos of specs that fully passed, to keep artifacts small (vlaams pattern).
      on("after:spec", (_spec, results) => {
        if (results && results.video) {
          const failed = results.tests.some((t) =>
            t.attempts.some((a) => a.state === "failed"),
          );
          if (!failed) {
            try {
              fs.unlinkSync(results.video);
            } catch {
              /* ignore */
            }
          }
        }
      });
    },
  },
  reporter: "cypress-multi-reporters",
  reporterOptions: { configFile: "reporter-config.json" },
  // The OIDC login flow crosses to the auth subdomain; Cypress needs this for cy.origin.
  chromeWebSecurity: false,
  video: true,
  screenshotOnRunFailure: true,
});
