---
- name: ensure gatus configuration directory exists
  file:
    path: "{{ gatus_config_dir }}"
    state: directory
    owner: "{{ docker_compose_userid }}"
    group: "{{ docker_compose_usergid }}"
  when:
    - (use_gatus | default(false) | bool) or (groups['gatus'] is defined and groups['gatus'] | length > 0)
  tags:
    - docker-compose
    - gatus

- name: ensure nginx directories exist for docker vhost generation
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_compose_userid }}"
    group: "{{ docker_compose_usergid }}"
  with_items:
    - "{{ nginx_conf_dir }}/conf.d"
    - "{{ nginx_conf_dir }}/sites-enabled"
    - "{{ nginx_conf_dir }}/sites-available"
  tags:
    - docker-compose
