#!/usr/bin/env python3
"""
Generate local/localhost inventories from lademo template.
Transforms multi-host docker_compose setup to single localhost setup.

Usage:
    python3 scripts/create_local_inventory.py > inventories/local/hosts
    python3 scripts/create_local_inventory.py dev > inventories/dev/hosts
"""

# Map of service key to hostname alias for full inventory
SERVICES_FULL = {
    "collectory": "localhost.collectory",
    "ala_hub": "localhost.biocache_hub",
    "biocache_service": "localhost.biocache_service",
    "lists": "localhost.species_list",
    "logger": "localhost.logger",
    "cas": "localhost.cas",
    "alerts": "localhost.alerts",
    "branding": "localhost.branding",
    "ala_bie": "localhost.bie_hub",
    "bie_index": "localhost.bie_index",
    "regions": "localhost.regions",
    "sds": "localhost.sds",
    "pipelines": "localhost.pipelines",
    "spark": "localhost.spark",
    "hadoop": "localhost.hadoop",
    "namematching_service": "localhost.namematching_service",
    "sensitive_data_service": "localhost.sensitive_data_service",
    "gatus": "localhost.gatus",
    "portainer": "localhost.portainer",
    "cassandra": "localhost.cassandra3",
    "images": "localhost.image_service",
    "solrcloud": "localhost.solrcloud",
    "zookeeper": "localhost.zookeeper",
    "spatial": "localhost.spatial",
    "doi": "localhost.doi_service",
    "data_quality": "localhost.data_quality",
    "docker_compose": "localhost.docker_compose",
}

# Minimal dev inventory (CAS + Collectory + Branding)
SERVICES_DEV = {
    "cas": "localhost.cas",
    "collectory": "localhost.collectory",
    "branding": "localhost.branding",
    "docker_compose": "localhost.docker_compose",
}

# Mapping from service key to Ansible group name
GROUP_MAPPING = {
    "collectory": "collectory",
    "ala_hub": "biocache-hub",
    "biocache_service": "biocache-service-clusterdb",
    "bie_hub": "bie-hub",
    "bie_index": "bie-index",
    "image_service": "image-service",
    "species_list": "species-list",
    "regions": "regions",
    "logger": "logger-service",
    "solrcloud": "solrcloud",
    "zookeeper": "zookeeper",
    "cas": "cas-servers",
    "spatial": "spatial",
    "alerts": "alerts-service",
    "doi_service": "doi-service",
    "sds": "sds",
    "pipelines": "pipelines",
    "spark": "spark",
    "hadoop": "hadoop",
    "data_quality": "data_quality_filter_service",
    "namematching_service": "namematching-service",
    "sensitive_data_service": "sensitive-data-service",
    "branding": "branding",
    "cassandra3": "cassandra3",
    "gatus": "gatus",
    "portainer": "portainer",
}


def generate_hosts_ini(services_dict, mode="full"):
    """Generate hosts.ini content from services dict"""
    lines = [
        "#",
        "# This file was autogenerated by scripts/create_local_inventory.py",
        "# Based on the lademo inventory pattern but with localhost",
        "# To regenerate with new services, update scripts/create_local_inventory.py",
        "#",
        "# NOTE: When multiple services are deployed on the same physical server,",
        "# this inventory uses hostname aliases to prevent Ansible variable conflicts.",
        "#",
        "# Aliases follow the pattern: localhost.<service-name>",
        "# Each alias points to localhost via ansible_host.",
        "#",
        "",
        "[all]",
    ]

    # Add all hosts in sorted order
    for alias in sorted(services_dict.values()):
        lines.append(f"{alias} ansible_host=localhost ansible_connection=local")

    lines.append("")
    lines.append("# Service groups")

    # Generate group sections for each service
    # Track which groups we've created to avoid duplicates
    created_groups = set()

    for service_key in sorted(services_dict.keys()):
        alias = services_dict[service_key]
        group_name = GROUP_MAPPING.get(service_key, service_key)

        # Skip if we already created this group
        if group_name in created_groups:
            continue
        created_groups.add(group_name)

        lines.append("")
        lines.append(f"[{group_name}]")
        if service_key == "cas":
            lines.append(f"{alias} nginx_vhost_fast_mode=false")
        else:
            lines.append(alias)

    # Docker compose groups and docker_compose_hosts configuration
    lines.extend(
        [
            "",
            "[docker_compose]",
            "localhost.docker_compose",
            "",
            "[docker-common]",
            "",
            "[docker_compose_hosts:children]",
            "docker_compose",
            "",
            "[docker_compose_hosts:vars]",
            "deployment_type = container",
            "# Database overrides for Docker Compose (using container names from la-docker-compose)",
            "collectory_db_host_address = la_mysql",
            "collectory_db_host = la_mysql",
            "logger_db_hostname = la_mysql",
            "specieslist_db_hostname = la_mysql",
            "alerts_db_hostname = la_mysql",
            "webapi_db_hostname = la_mysql",
            "doi_db_hostname = la_mysql",
            "cas_db_hostname = la_mysql",
            "user_store_db_hostname = la_mysql",
            "ticket_registry_db_hostname = la_mysql",
            "apikey_db_hostname = la_mysql",
            "# Mongodb overrides",
            "cas_audit_host=la_mongodb",
            "cas_spring_session_host=la_mongodb",
            "cas_tickets_host=la_mongodb",
            "cas_services_host=la_mongodb",
            "# Postgresql overrides",
            "postgresql_host = la_postgres",
            "layers_db_host = la_postgres",
            "geonetwork_host = la_postgres",
            "spatial_db_host = la_postgres",
            "",
        ]
    )

    return "\n".join(lines)


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "dev":
        content = generate_hosts_ini(SERVICES_DEV, mode="dev")
    else:
        content = generate_hosts_ini(SERVICES_FULL, mode="full")

    print(content)
