#!/usr/bin/env python3
"""Regenerate CHANGELOG.md from the release tags and the commits between them.

Each entry has the annotated tag message as its release notes (what was validated,
by which green build) followed by every commit in the range, grouped by type from
its conventional-commit prefix. Everything comes from git, so the file can be
rebuilt at any time and a new release only needs its annotated tag first:

    git tag -a vX.Y.Z <green-sha> -F notes.txt
    scripts/gen-changelog.py > CHANGELOG.md

Commits after the newest tag are listed under "Unreleased".
"""
import re
import subprocess
import sys

REPO_URL = "https://github.com/living-atlases/la-docker-compose"
FOLD_OVER = 30  # ranges longer than this are folded in <details>

GROUPS = [
    ("Features", {"feat", "add", "added", "auto-detect", "build", "perf"}),
    ("Fixes", {"fix", "fixes", "correct", "harden", "guard", "revert", "restore",
               "recreate", "remove", "clean", "stop", "never", "let", "pass",
               "refresh"}),
    ("Tests and CI", {"test", "ci", "e2e", "diag"}),
    ("Documentation", {"docs", "changelog.md"}),
    ("Maintenance", {"chore", "refactor", "cleanup", "update", "improve", "more",
                     "trying"}),
]
CONVENTIONAL = re.compile(r"^(?P<type>[A-Za-z]+)(?:\((?P<scope>[^)]*)\))?!?:\s*(?P<rest>.*)$")


def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def clean(text):
    return text.replace("\u2014", "-").replace("\u2013", "-").replace("\r", "")


def classify(subject):
    """Return (group, display text) for a commit subject."""
    m = CONVENTIONAL.match(subject)
    if m and " " not in m.group("type"):
        kind = m.group("type").lower()
        scope = m.group("scope")
        text = f"**{scope}**: {m.group('rest')}" if scope else m.group("rest")
    else:
        first = subject.split()[0].rstrip(":").lower() if subject.split() else ""
        kind, text = first, subject
        if first.startswith("test-"):
            kind = "test"
    for name, kinds in GROUPS:
        if kind in kinds:
            return name, text
    return "Other changes", text


def commits(rev_range):
    out = git("log", "--no-merges", "--format=%h%x09%H%x09%s", rev_range)
    return [line.split("\t", 2) for line in out.splitlines() if line.strip()]


def render_commits(entries):
    grouped = {}
    for short, full, subject in entries:
        name, text = classify(clean(subject))
        grouped.setdefault(name, []).append(f"- {text} ([{short}]({REPO_URL}/commit/{full}))")
    lines = []
    for name in [g for g, _ in GROUPS] + ["Other changes"]:
        if name in grouped:
            lines += [f"#### {name}", ""] + grouped[name] + [""]
    return lines


def section(tag, prev, notes_title, notes_body, date):
    rev_range = f"{prev}..{tag}" if prev else tag
    entries = commits(rev_range)
    lines = [f'<a name="{tag}"></a>', "", f"## {tag} - {date}", ""]
    if notes_title:
        lines += [f"**{notes_title}**", ""]
    if notes_body:
        lines += [notes_body, ""]
    since = f" since {prev}" if prev else ""
    lines += [f"### Commits ({len(entries)}{since})", ""]
    body = render_commits(entries)
    if len(entries) > FOLD_OVER:
        lines += ["<details>", f"<summary>All {len(entries)} commits, by type</summary>", ""]
        lines += body + ["</details>", ""]
    else:
        lines += body
    return lines


def main():
    tags = git("tag", "--sort=-v:refname").split()
    out = [
        "# Changelog",
        "",
        "Changes per release tag, newest first. A tag is only cut on a commit a green",
        "la-docker-compose-tests build validated. Each entry opens with its tag's release",
        "notes (which build validated it and what changed), then lists every commit since",
        "the previous tag, grouped by type. Generated by scripts/gen-changelog.py; do not",
        "edit by hand, write the notes in the annotated tag instead.",
        "",
    ]
    unreleased = commits(f"{tags[0]}..HEAD") if tags else []
    out += ['<a name="unreleased"></a>', "", "## Unreleased", ""]
    out += render_commits(unreleased) if unreleased else ["Nothing yet.", ""]
    for i, tag in enumerate(tags):
        prev = tags[i + 1] if i + 1 < len(tags) else None
        date = git("for-each-ref", f"refs/tags/{tag}", "--format=%(creatordate:short)").strip()
        title = body = ""
        if git("cat-file", "-t", tag).strip() == "tag":  # annotated; a lightweight tag has no notes
            subject = clean(git("for-each-ref", f"refs/tags/{tag}", "--format=%(contents:subject)").strip())
            body = clean(git("for-each-ref", f"refs/tags/{tag}", "--format=%(contents:body)").strip())
            title = re.sub(r"^" + re.escape(tag) + r"\s*[-:]*\s*", "", subject).strip()
        out += section(tag, prev, title, body, date)
    sys.stdout.write("\n".join(out).rstrip("\n") + "\n")


if __name__ == "__main__":
    main()
