#!/usr/bin/env bash
# Validate that config generation produces correct Docker-ready output.
#
# Checks performed:
#   1. molecule test -s unit    (normalize-hostnames.yml unit tests)
#   2. ansible-playbook config-gen.yml  (generate configs locally)
#   3. No localhost/127.0.0.1 in DB connection strings
#   4. No localhost/127.0.0.1 in nginx upstream blocks
#   5. docker compose config   (compose file syntax validation)
#
# Usage: scripts/validate-config-gen.sh [INVENTORY] [OUTPUT_DIR]
#   INVENTORY  defaults to inventories/testing/lademo-inventories (yo living-atlas generated)
#   OUTPUT_DIR defaults to /data/la-docker-config-test
set -euo pipefail

INVENTORY="${1:-inventories/testing/lademo-inventories}"
# NOTE: Docker Desktop on Linux does not share /tmp by default, so the default
# output lives under /data (a shared path) to ensure the cert-validator container
# can mount it. If using Docker Desktop, also add this dir to Settings > Resources > File sharing.
OUTPUT_DIR="${2:-/data/la-docker-config-test}"
VENV_MOLECULE="${VENV_MOLECULE:-.venv-molecule}"
COMPOSE_DIR="${OUTPUT_DIR}"

# ── Colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

pass() { echo -e "${GREEN}✔ PASS${RESET} $*"; }
fail() { echo -e "${RED}✗ FAIL${RESET} $*"; FAILURES=$((FAILURES + 1)); }
section() { echo -e "\n${CYAN}${BOLD}=== $* ===${RESET}"; }
warn() { echo -e "${YELLOW}⚠ WARN${RESET} $*"; }

FAILURES=0

# ── Check 1: Molecule unit tests ──────────────────────────────────────────────
section "Check 1: Molecule unit tests (normalize-hostnames.yml)"

MOLECULE_BIN=""
if [[ -x "$VENV_MOLECULE/bin/molecule" ]]; then
  MOLECULE_BIN="$VENV_MOLECULE/bin/molecule"
elif command -v molecule >/dev/null 2>&1; then
  MOLECULE_BIN="molecule"
fi

if [[ -z "$MOLECULE_BIN" ]]; then
  warn "molecule not found. Run scripts/setup-molecule.sh to install it."
  warn "Skipping molecule unit tests."
else
  if "$MOLECULE_BIN" test -s unit; then
    pass "Molecule unit tests passed"
  else
    fail "Molecule unit tests failed"
  fi
fi

# ── Validate inventory exists ─────────────────────────────────────────────────
if [[ ! -e "$INVENTORY" ]]; then
  echo -e "${RED}ERROR: Inventory path not found: $INVENTORY${RESET}" >&2
  echo "  Try: yo living-atlas --replay-dont-ask --force  (in the inventory directory)" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

# ── Check 2: Config generation ────────────────────────────────────────────────
section "Check 2: Config generation (ansible-playbook config-gen.yml)"

# Use ansiblew from inventory directory (generated by yo living-atlas).
# ansiblew --ladocker=<repo> runs config-gen.yml + site.yml when 'docker_compose all' is passed.
# Fall back to plain ansible-playbook if ansiblew not found (e.g. non-yo inventory).
INVENTORY_ANSIBLEW="$(realpath "$INVENTORY" 2>/dev/null)/ansiblew"
LADOCKER_DIR="$(realpath "$(dirname "$0")/.." 2>/dev/null)"

if [[ -x "$INVENTORY_ANSIBLEW" ]]; then
  # ansiblew uses relative paths (lademo-*.ini) so must be run from the inventory directory
  INVENTORY_ABS="$(realpath "$INVENTORY")"
  pushd "$INVENTORY_ABS" >/dev/null
  if ANSIBLE_CONFIG="$LADOCKER_DIR/playbooks/ansible.cfg" \
    ./ansiblew \
    --alainstall=/dev/null \
    --ladocker="$LADOCKER_DIR" \
    --nodryrun \
    --docker-local \
    --properties \
    --tags=docker-compose,properties-file \
    --skip=docker,db-init,deploy \
    --extra="docker_compose_data_dir=$OUTPUT_DIR data_dir=$OUTPUT_DIR build_images=false${ANSIBLE_LOCAL_EXTRA_VARS:+ $ANSIBLE_LOCAL_EXTRA_VARS}" \
    all; then
    popd >/dev/null
    pass "Config generation completed"
  else
    popd >/dev/null
    fail "Config generation failed"
    echo -e "${RED}Aborting remaining checks - no output to analyse.${RESET}"
    exit 1
  fi
else
  # Fallback: plain ansible-playbook with explicit -i flags
  INVENTORY_FLAGS=()
  if [[ -d "$INVENTORY" ]]; then
    while IFS= read -r f; do INVENTORY_FLAGS+=(-i "$f"); done < <(find "$INVENTORY" -maxdepth 1 -name "*.ini" | sort)
  else
    INVENTORY_FLAGS=(-i "$INVENTORY")
  fi
  if ANSIBLE_CONFIG=playbooks/ansible.cfg ansible-playbook \
    "${INVENTORY_FLAGS[@]}" \
    playbooks/config-gen.yml \
    --tags docker-compose \
    -e deployment_type=container \
    -e docker_compose_data_dir="$OUTPUT_DIR" \
    -e data_dir="$OUTPUT_DIR"; then
    pass "Config generation completed"
  else
    fail "Config generation failed"
    echo -e "${RED}Aborting remaining checks - no output to analyse.${RESET}"
    exit 1
  fi
fi

# ── Check 3: No localhost in DB connection strings ────────────────────────────
section "Check 3: No localhost/127.0.0.1 in DB connection strings"

db_bad="$(grep -R -E "(mongodb://|jdbc:(mysql|postgresql)://|mysql://|postgresql://).*(localhost|127\.0\.0\.1)" \
  --exclude-dir=solr \
  "$OUTPUT_DIR/" 2>/dev/null || true)"
if [[ -n "$db_bad" ]]; then
  fail "localhost found in DB connection strings:"
  echo "$db_bad" | sed 's/^/    /'
else
  pass "No localhost in DB connection strings"
fi

echo "  MongoDB URIs:    $(grep -Roh 'mongodb://[^"'"'"'[:space:]]*' "$OUTPUT_DIR/" 2>/dev/null | sort -u | tr '\n' ' ' || echo '(none)')"
echo "  MySQL URIs:      $(grep -Roh 'jdbc:mysql://[^"'"'"'[:space:]]*' "$OUTPUT_DIR/" 2>/dev/null | sort -u | tr '\n' ' ' || echo '(none)')"
echo "  PostgreSQL URIs: $(grep -Roh 'jdbc:postgresql://[^"'"'"'[:space:]]*' "$OUTPUT_DIR/" 2>/dev/null | sort -u | tr '\n' ' ' || echo '(none)')"

# ── Check 4: No localhost in nginx upstream blocks ────────────────────────────
section "Check 4: No localhost/127.0.0.1 in nginx upstream blocks"

nginx_conf_files="$(find "$OUTPUT_DIR" -name "*.conf" -path "*/nginx/*" 2>/dev/null || true)"
if [[ -z "$nginx_conf_files" ]]; then
  warn "No nginx config files found in $OUTPUT_DIR - skipping nginx upstream check"
else
  nginx_bad="$(echo "$nginx_conf_files" | xargs grep -E "upstream[[:space:]]|proxy_pass[[:space:]]" 2>/dev/null | \
    grep -E "(localhost|127\.0\.0\.1)" || true)"
  if [[ -n "$nginx_bad" ]]; then
    fail "localhost found in nginx upstream/proxy_pass:"
    echo "$nginx_bad" | sed 's/^/    /'
  else
    pass "No localhost in nginx upstream blocks"
  fi
fi

# ── Check 5: Docker Compose config syntax ────────────────────────────────────
section "Check 5: Docker Compose syntax validation"

if [[ -f "$COMPOSE_DIR/docker-compose.yml" ]]; then
  if docker compose -f "$COMPOSE_DIR/docker-compose.yml" config --quiet 2>/dev/null; then
    pass "docker compose config syntax valid"
  else
    fail "docker compose config syntax error in $COMPOSE_DIR/docker-compose.yml"
  fi
else
  warn "No docker-compose.yml found at $COMPOSE_DIR - skipping compose syntax check"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
if [[ $FAILURES -eq 0 ]]; then
  echo -e "${GREEN}${BOLD}✔ ALL CHECKS PASSED${RESET}"
  exit 0
else
  echo -e "${RED}${BOLD}✗ $FAILURES CHECK(S) FAILED${RESET}"
  exit 1
fi

